#!/bin/sh

# tailscale_pia_bypass.sh
# Script to configure OpenWrt to bypass the PIA VPN for Tailscale traffic
# This relies on Policy-Based Routing (pbr) to maintain the WAN routing table

echo "Configuring Tailscale PIA Bypass..."

# 1. Enable PBR
echo "Enabling PBR..."
uci set pbr.config.enabled='1'
if ! uci show pbr.config.ignored_interface 2>/dev/null | grep -q "'tailscale'"; then
    uci add_list pbr.config.ignored_interface='tailscale'
fi
uci commit pbr

# 2. Configure network IP rules via hotplug
echo "Configuring OpenWrt IP rules for Tailscale fwmark via hotplug..."

# Configure network interface protocol to prevent IP loss
if [ "$(uci -q get network.tailscale.proto)" = "none" ]; then
    uci set network.tailscale.proto='unmanaged'
    uci commit network
fi

cat << 'EOF' > /etc/hotplug.d/iface/99-tailscale-bypass
#!/bin/sh
[ "$ACTION" = "ifup" ] || exit 0

# Allow Tailscale to access local LAN subnets
if ! ip rule show | grep -q '5190:'; then
    ip rule add fwmark 0x80000/0xff0000 lookup main suppress_prefixlength 0 pref 5190 2>/dev/null
fi

# Route external Tailscale traffic through PBR's physical WAN table (256)
if ! ip rule show | grep -q '5200:'; then
    ip rule add fwmark 0x80000/0xff0000 lookup 256 pref 5200 2>/dev/null
fi
EOF
chmod +x /etc/hotplug.d/iface/99-tailscale-bypass

# Apply rules immediately
ACTION=ifup /etc/hotplug.d/iface/99-tailscale-bypass

# 3. Configure Firewall Forwarding for Tailscale Exit Node
echo "Configuring firewall forwarding for Tailscale exit node..."
if ! uci show firewall | grep -q "src='tailscale'.*dest='pia_exit'"; then
    uci add firewall forwarding >/dev/null
    uci set firewall.@forwarding[-1].src='tailscale'
    uci set firewall.@forwarding[-1].dest='pia_exit'
fi
if ! uci show firewall | grep -q "src='tailscale'.*dest='wan'"; then
    uci add firewall forwarding >/dev/null
    uci set firewall.@forwarding[-1].src='tailscale'
    uci set firewall.@forwarding[-1].dest='wan'
fi
if ! uci show firewall | grep -q "dest_port='41641'"; then
    uci add firewall rule >/dev/null
    uci set firewall.@rule[-1].name='Allow-Tailscale'
    uci set firewall.@rule[-1].src='wan'
    uci set firewall.@rule[-1].target='ACCEPT'
    uci set firewall.@rule[-1].proto='udp'
    uci set firewall.@rule[-1].dest_port='41641'
fi
uci commit firewall

# 4. Prevent Tailscale from overwriting router DNS
echo "Configuring Tailscale to prevent DNS takeover..."
# Disable Tailscale DNS acceptance
tailscale set --accept-dns=false 2>/dev/null || true

# Restore OpenWrt's native resolv.conf if Tailscale overwrote it
if grep -q "generated by tailscale" /etc/resolv.conf 2>/dev/null; then
    echo "Restoring native /etc/resolv.conf..."
    rm -f /etc/resolv.conf
    ln -s /tmp/resolv.conf /etc/resolv.conf
    /etc/init.d/dnsmasq restart
fi

# 5. Restart services
echo "Restarting PBR and Firewall..."
/etc/init.d/pbr enable
/etc/init.d/pbr restart
/etc/init.d/firewall restart

echo "Tailscale PIA Bypass configuration complete."
echo "Use 'tailscale netcheck' to verify DERP connectivity."
